public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog + 4;
        cat = cat + 4;
        paper = paper+4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog - 3.5;
        cat = cat - 1/6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend +2;
        System.out.println(friend);
        friend = (friend +2)/7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog=10*frog;
        System.out.println(frog);
        frog=frog/3.5;
        System.out.println(frog);
        frog = frog+4;
        System.out.println(frog);
        var boxerWeight1 = 78.2;
        var boxerWeight2 = 82.7;
        var totalWeight = boxerWeight1+boxerWeight2;
        System.out.println(totalWeight);
        var differenceWeight = boxerWeight2-boxerWeight1;
        System.out.println(differenceWeight);
        var remain = boxerWeight2/boxerWeight1;
        System.out.println(remain);
        var totalWorkTime = 640;
        var workTimeOnePeople  = 8;
        var allWorker = totalWorkTime/workTimeOnePeople;
        System.out.println("Всего работников в компании" + allWorker + "человек" );
        var newWorker = allWorker+94;
        System.out.println("С новыми сотрудниками в компании работает" + newWorker + "человек");
    }
}